# AMBF CRTK configuration file template 
# Author: Hisashi Ishida
# Date: 02.09.2024

# Interfaces used for this plugin
interface:
- SRC/needle
- SRC/psm1
- SRC/psm2

SRC/needle:
  measured_cp:
    # Name of Rigidbody in AMBF 
    rigidbody: Needle

SRC/psm1:
  measured_cp:
    rigidbody: psm1/BODY tool yaw link
  measured_js:
    joints:
    - psm1/BODY pitch end link-main insertion link
    - psm1/BODY main insertion link-tool roll link
    - psm1/BODY tool roll link-tool pitch link
    - psm1/BODY tool pitch link-tool yaw link
    - psm1/BODY tool yaw link-tool gripper1 link
    - psm1/BODY tool yaw link-tool gripper2 link
  servo_cp:
    rigidbody: psm1/BODY tool yaw link
  servo_jp:
    joints:
    - psm1/BODY pitch end link-main insertion link
    - psm1/BODY main insertion link-tool roll link
    - psm1/BODY tool roll link-tool pitch link
    - psm1/BODY tool pitch link-tool yaw link
    - psm1/BODY tool yaw link-tool gripper1 link
    - psm1/BODY tool yaw link-tool gripper2 link
  
SRC/psm2:
  measured_cp:
    rigidbody: psm2/BODY tool yaw link
  measured_js:
    joints:
    - psm2/BODY pitch end link-main insertion link
    - psm2/BODY main insertion link-tool roll link
    - psm2/BODY tool roll link-tool pitch link
    - psm2/BODY tool pitch link-tool yaw link
    - psm2/BODY tool yaw link-tool gripper1 link
    - psm2/BODY tool yaw link-tool gripper2 link
  servo_cp:
    rigidbody: psm2/BODY tool yaw link
  servo_jp:
    joints:
    - psm2/BODY pitch end link-main insertion link
    - psm2/BODY main insertion link-tool roll link
    - psm2/BODY tool roll link-tool pitch link
    - psm2/BODY tool pitch link-tool yaw link
    - psm2/BODY tool yaw link-tool gripper1 link
    - psm2/BODY tool yaw link-tool gripper2 link