# AMBF CRTK configuration file template for CRTK_simulator_plugin
# Author: Hisashi Ishida
# Date: 03.14.2024
# Usage: add the path (build/lib_CRTK_simulator_plugin.so) and add --conf ../example/SRC_config.yaml
# Interfaces used for this plugin
interface:
- SRC/needle
- SRC/psm1
- SRC/psm2

SRC/needle:
  measured_cp:
  [
    {
      # Name of Rigidbody in AMBF 
      rigidbody: BODY Needle
    }
  ]

SRC/psm1:
  measured_cp:
  [
    {
      rigidbody: psm1/BODY tool yaw link
    }
  ]
  measured_js:
    joints:
    - psm1/JOINT pitch end link-main insertion link
    - psm1/JOINT main insertion link-tool roll link
    - psm1/JOINT tool roll link-tool pitch link
    - psm1/JOINT tool pitch link-tool yaw link
    - psm1/JOINT tool yaw link-tool gripper left link
    - psm1/JOINT tool yaw link-tool gripper right link

  servo_cp:
  [
    {
    rigidbody: psm1/BODY tool yaw link
    }
  ]

  servo_jp:
    joints:
    - psm1/JOINT pitch end link-main insertion link
    - psm1/JOINT main insertion link-tool roll link
    - psm1/JOINT tool roll link-tool pitch link
    - psm1/JOINT tool pitch link-tool yaw link
    - psm1/JOINT tool yaw link-tool gripper left link
    - psm1/JOINT tool yaw link-tool gripper right link
  
SRC/psm2:
  measured_cp:
  [
    {
      rigidbody: psm2/BODY tool yaw link
    }
  ]
  
  measured_js:
    joints:
    - psm2/JOINT pitch end link-main insertion link
    - psm2/JOINT main insertion link-tool roll link
    - psm2/JOINT tool roll link-tool pitch link
    - psm2/JOINT tool pitch link-tool yaw link
    - psm2/JOINT tool yaw link-tool gripper left link
    - psm2/JOINT tool yaw link-tool gripper right link

  servo_cp:
  [
    {
      rigidbody: psm2/BODY tool yaw link
    }
  ]

  servo_jp:
    joints:
    - psm2/JOINT pitch end link-main insertion link
    - psm2/JOINT main insertion link-tool roll link
    - psm2/JOINT tool roll link-tool pitch link
    - psm2/JOINT tool pitch link-tool yaw link
    - psm2/JOINT tool yaw link-tool gripper left link
    - psm2/JOINT tool yaw link-tool gripper right link