# AMBF CRTK configuration file template for CRTK_simulator_plugin
# Author: Hisashi Ishida
# Date: 03.14.2024
# Usage: add the path (build/lib_CRTK_simulator_plugin.so) and add --conf ../example/simulator_plugin/CRTK_config_simple.yaml


# Interfaces used for this plugin
interface:
- REMS/Research


# For Interface "REMS/Research"
REMS/Research:
  measured_cp:
    # Additonal namespace
    # rostopic name will be "REMS/Research/delta/measured_cp" 
    namespace: delta

    # Name of Rigidbody in AMBF 
    rigidbody: Endoscope Tip

  measured_js:
    # Name of joints in AMBF
    joints:
    - carriage3_joint
    - carriage1_joint
    - carriage2_joint
    - roll_joint


  measured_cf:
    # Name of Rigidbody in AMBF 
    rigidbody: Endoscope Tip
