# AMBF CRTK configuration file template for CRTK_model_plugin
# Author: Hisashi Ishida
# Date: 04.04.2025


# Interfaces used for this plugin
interface:
- PSM1

PSM1:
  measured_cp: [
    {
      rigidbody: psm1/BODY tool yaw link,
      namespace: /PSM1/, # [Optional] Override namespace "/PSM1/measured_cp"
      reference: CameraFrame
    },
    # {
    #   rigidbody: psm1/BODY base link,
    #   reference: CameraFrame
    # }
  ]

  setpoint_cp: [
    {
      rigidbody: psm1/BODY tool yaw link,
      namespace: /PSM1/, # [Optional] Override namespace "/PSM1/measured_cp"
      reference: CameraFrame
    }
  ]

  measured_js: [
    {
      namespace: /PSM1,
      joints: [
        psm1/JOINT pitch end link-main insertion link,
        psm1/JOINT main insertion link-tool roll link,
        psm1/JOINT tool roll link-tool pitch link,
        psm1/JOINT tool pitch link-tool yaw link,
        psm1/JOINT tool yaw link-tool gripper left link,
        psm1/JOINT tool yaw link-tool gripper right link,
      ]
    },
    {
      joints: [
        psm1/JOINT tool yaw link-tool gripper left link,
        psm1/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM1/gripper
    }
  ]
    
  servo_cp:
  [
    {
      rigidbody: psm1/BODY tool yaw link,
      namespace: /PSM1/, # [Optional] Override namespace "/PSM1/measured_cp"
      reference: CameraFrame
    }
  ]

  servo_jp: [
    {
      joints: [
        psm1/JOINT pitch end link-main insertion link,
        psm1/JOINT main insertion link-tool roll link,
        psm1/JOINT tool roll link-tool pitch link,
        psm1/JOINT tool pitch link-tool yaw link,
        psm1/JOINT tool yaw link-tool gripper left link,
        psm1/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM1/,
    }, 
    {
      joints: [
        psm1/JOINT tool yaw link-tool gripper left link,
        psm1/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM1/gripper,
    }, 

  ]
    