# AMBF CRTK configuration file template for CRTK_simulator_plugin
# Author: Hisashi Ishida
# Date: 03.14.2024
# Usage: add the path (build/lib_CRTK_simulator_plugin.so) and add --conf ../example/SRC_config.yaml
# Interfaces used for this plugin
interface:
- psm1

psm1:
  measured_cp: [
    {
      rigidbody: psm1/BODY tool yaw link,
      reference: CameraFrame
    },
    # {
    #   rigidbody: psm1/BODY base link,
    #   reference: CameraFrame
    # }
  ]

  setpoint_cp: [
    {
      rigidbody: psm1/BODY tool yaw link,
      reference: CameraFrame
    }
  ]

  measured_js:
    joints:
    - psm1/JOINT pitch end link-main insertion link
    - psm1/JOINT main insertion link-tool roll link
    - psm1/JOINT tool roll link-tool pitch link
    - psm1/JOINT tool pitch link-tool yaw link
    - psm1/JOINT tool yaw link-tool gripper left link
    - psm1/JOINT tool yaw link-tool gripper right link
  servo_cp:
  [
    {
      rigidbody: psm1/BODY tool yaw link
    }
  ]

  servo_jp:
    joints:
    - psm1/JOINT pitch end link-main insertion link
    - psm1/JOINT main insertion link-tool roll link
    - psm1/JOINT tool roll link-tool pitch link
    - psm1/JOINT tool pitch link-tool yaw link
    - psm1/JOINT tool yaw link-tool gripper left link
    - psm1/JOINT tool yaw link-tool gripper right link