# AMBF CRTK configuration file template for CRTK_simulator_plugin
# Author: Hisashi Ishida
# Date: 03.14.2024
# Usage: add the path (build/lib_CRTK_simulator_plugin.so) and add --conf ../example/SRC_config.yaml
# Interfaces used for this plugin
interface:
- PSM2

PSM2:
  measured_cp: [
    {
      rigidbody: psm2/BODY tool yaw link,
      namespace: /PSM2/,
      reference: CameraFrame
    },
  ]

  setpoint_cp: [
    {
      rigidbody: psm2/BODY tool yaw link,
      namespace: /PSM2/,
      reference: CameraFrame
    }
  ]
  
  measured_js: [
    {
      joints: [
        psm2/JOINT pitch end link-main insertion link,
        psm2/JOINT main insertion link-tool roll link,
        psm2/JOINT tool roll link-tool pitch link,
        psm2/JOINT tool pitch link-tool yaw link,
        psm2/JOINT tool yaw link-tool gripper left link,
        psm2/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM2/gripper

    },
    {
      joints: [
        psm2/JOINT tool yaw link-tool gripper left link,
        psm2/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM2/gripper
    },
  ]

  servo_cp:
  [
    {
      rigidbody: psm2/BODY tool yaw link,
      namespace: /PSM2/,
      reference: CameraFrame
    }
  ]

  servo_jp: [
    {
      joints: [
        psm2/JOINT pitch end link-main insertion link,
        psm2/JOINT main insertion link-tool roll link,
        psm2/JOINT tool roll link-tool pitch link,
        psm2/JOINT tool pitch link-tool yaw link,
        psm2/JOINT tool yaw link-tool gripper left link,
        psm2/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM2/gripper

    },
    {
      joints: [
        psm2/JOINT tool yaw link-tool gripper left link,
        psm2/JOINT tool yaw link-tool gripper right link,
      ],
      namespace: /PSM2/gripper
    },
  ]